[
    {
        "id": 367930039,
        "name": "CVE-2021-31166",
        "full_name": "0vercl0k\/CVE-2021-31166",
        "owner": {
            "login": "0vercl0k",
            "id": 1476421,
            "avatar_url": "https:\/\/avatars.githubusercontent.com\/u\/1476421?v=4",
            "html_url": "https:\/\/github.com\/0vercl0k"
        },
        "html_url": "https:\/\/github.com\/0vercl0k\/CVE-2021-31166",
        "description": "Proof of concept for CVE-2021-31166, a remote HTTP.sys use-after-free triggered remotely.",
        "fork": false,
        "created_at": "2021-05-16T16:15:56Z",
        "updated_at": "2021-05-17T15:07:20Z",
        "pushed_at": "2021-05-16T20:48:28Z",
        "stargazers_count": 246,
        "watchers_count": 246,
        "forks_count": 53,
        "forks": 53,
        "watchers": 246,
        "score": 0
    },
    {
        "id": 368156601,
        "name": "CVE-2021-31166",
        "full_name": "An0ny-m0us\/CVE-2021-31166",
        "owner": {
            "login": "An0ny-m0us",
            "id": 41460798,
            "avatar_url": "https:\/\/avatars.githubusercontent.com\/u\/41460798?v=4",
            "html_url": "https:\/\/github.com\/An0ny-m0us"
        },
        "html_url": "https:\/\/github.com\/An0ny-m0us\/CVE-2021-31166",
        "description": "PoC for CVE-2021-31166, a remote HTTP.sys use-after-free triggered remotely. Although it was defined as remote command execution, it can only cause the system to crash.",
        "fork": false,
        "created_at": "2021-05-17T11:12:45Z",
        "updated_at": "2021-05-17T14:49:26Z",
        "pushed_at": "2021-05-17T11:30:26Z",
        "stargazers_count": 1,
        "watchers_count": 1,
        "forks_count": 0,
        "forks": 0,
        "watchers": 1,
        "score": 0
    }
]